
# Project name and version


name: 'documentations'
version: '0.0.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'


# These configurations specify where dbt should look for different types of files.
# The `model-paths` config,
docs-paths: ["docs"]
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]


log-path:  "/home/astro/documentations/logs"
target-path: "/home/astro/documentations/target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "/home/astro/documentations/dbt_packages"
  - "/home/astro/documentations/target"
# packages-install-path: Specify which path dbt should use for storing and finding modules.
packages-install-path:  "/home/astro/documentations/dbt_packages"

# To toggle model quoting, set `database`, `identifier`
# and `schema` to `true` or `false`.
quoting:
  database: false
  identifier: false
  schema: false

vars:

seeds:
# Enable quoting of seed columns in your project
   quote_columns: True
   documentations:
      enabled: true

# tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
   documentations:
      enabled: true
