site_name: Customer Analytics Knowledge Network
theme:
  name: material
  custom_dir: overrides
  logo: assets/autodesk.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    edit: material/pencil
    view: material/eye
    tag:
      default: material/tag
    

plugins:
    - awesome-pages
    - search:
        lang: en
    - exclude-search:
        exclude:
          - domains/*
          - cakn-document-templates/*
    - glightbox
    - techdocs-core
    - tags:
        tags_file: tags.md

repo_url: https://git.autodesk.com/dpe/adp-astro-cso-analytics/tree/master/dags/dbt
edit_uri: documentations/eio_documentation/docs
extra_css:
  - stylesheets/extra.css
  - stylesheets/heading-icons.css
  - stylesheets/dark-mode.css
  - stylesheets/info-card.css
  - stylesheets/artifakt-font.css
extra_javascript:
  - javascripts/info-card-sidebar.js

extra:
  comments:
    enabled: true
    # defaults to utterances unless replaced with mode: giscus
    mode: utterances
    type: issues


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      toc_depth: 3
      permalink: '#'
      permalink_title: Anchor link to this section for reference
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
nav:
  - Home: index.md