apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: eax-de-team
  description: The infra business unit
spec:
  type: business-unit
  profile:
    displayName: DE Team
    email: eda.eax.de@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  #parent: ops
  children: []
  #members: [akhil]